import {z} from 'zod';
import {type Row,type State,today,daysLeft,endDate,memberStatus} from './model';
import {hashPassword} from './crypto';
const text=z.string().trim().max(1000),name=z.string().trim().min(1).max(120),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T00:00:00Z');return !Number.isNaN(+d)&&d.toISOString().slice(0,10)===v},'Enter a valid date'),amount=z.coerce.number().finite().min(0).max(10000000),phone=z.string().trim().max(30).refine(v=>!v||/^[+\d()\s-]{7,30}$/.test(v),'Enter a valid contact number');
const person=z.object({firstName:name,middleName:text.default(''),lastName:name,gender:z.enum(['Female','Male','Other','Prefer not to say']),birthDate:z.union([date,z.literal('')]).default(''),contact:phone,address:text.default(''),emergencyName:text.default(''),emergencyContact:phone.default(''),notes:text.default('')});
const membership=z.object({planId:name,start:date,discount:amount.default(0),method:name,reference:text.default(''),notes:text.default('')});
const payment=z.object({amount,method:name,reference:text.default('')});
export const publicAdmin=(a:Row)=>{const {passwordHash,...safe}=a;return safe};
function id(s:State,kind:string,prefix:string,size=5){s.counters[kind]=(s.counters[kind]||0)+1;return prefix+String(s.counters[kind]).padStart(size,'0')}
export function audit(s:State,actor:Row,action:string,module:string,recordId:string,previous:any=null,next:any=null){s.audits.unshift({id:id(s,'audit','AUD-',6),at:new Date().toISOString(),actor:actor.name,actorId:actor.id,action,module,recordId,previous,new:next,description:`${action} · ${recordId}`})}
function requireAdmin(actor:Row){if(actor.role!=='Super Admin')throw Error('Only a Super Admin can perform this action.')}
function member(s:State,id:string){const m=s.members.find(x=>x.id===id);if(!m)throw Error('Member not found.');return m}
function plan(s:State,id:string){const p=s.plans.find(x=>x.id===id&&x.active);if(!p)throw Error('Select an active membership plan.');return p}
function method(s:State,value:string){if(!s.settings.paymentMethods.includes(value))throw Error('Select an enabled payment method.')}
function recordPayment(s:State,actor:Row,data:Row){method(s,data.method);const p:Row={...data,id:id(s,'payment','PAY-',6),at:new Date().toISOString(),date:today(),recordedBy:actor.name,status:'Paid'};s.payments.unshift(p);return p}
function duplicate(s:State,p:Row,except?:string){return s.members.find(x=>x.id!==except&&((p.contact&&x.contact.replace(/\D/g,'')===p.contact.replace(/\D/g,''))||`${x.firstName} ${x.lastName}`.toLowerCase()===`${p.firstName} ${p.lastName}`.toLowerCase()))}
export function operate(s:State,actor:Row,action:string,input:Row):any {
 const now=new Date().toISOString();
 if(action==='member.create'||action==='walkin.convert'){
  const p=person.parse(input),d=membership.parse(input),pl=plan(s,d.planId);method(s,d.method);if(p.birthDate&&p.birthDate>today())throw Error('Birth date cannot be in the future.');if(d.discount>pl.price)throw Error('Discount exceeds the membership fee.');const dup=duplicate(s,p);if(dup)throw Error(`Possible duplicate member: ${dup.id}. Review the existing profile.`);
  const w=action==='walkin.convert'?s.walkins.find(x=>x.id===input.walkinId&&!x.memberId&&x.status!=='Cancelled'):null;if(action==='walkin.convert'&&!w)throw Error('Walk-in is unavailable or already converted.');
  const m={...p,id:id(s,'member','MTF-'),name:[p.firstName,p.middleName,p.lastName].filter(Boolean).join(' '),planId:pl.id,planName:pl.name,start:d.start,expiry:endDate(d.start,pl.duration),fee:pl.price,joined:today(),status:'Active',archived:false,lastCheckin:null};s.members.unshift(m);
  const pay=recordPayment(s,actor,{memberId:m.id,customer:m.name,type:'Membership Registration',amount:pl.price-d.discount,discount:d.discount,method:d.method,reference:d.reference,period:`${m.start} – ${m.expiry}`});s.memberships.unshift({id:id(s,'membership','MS-'),memberId:m.id,planId:pl.id,planName:pl.name,start:m.start,end:m.expiry,amount:pay.amount,paymentId:pay.id,at:now,recordedBy:actor.name,type:'Registration'});
  if(w){w.memberId=m.id;audit(s,actor,'Converted walk-in','Walk-ins',w.id,null,{memberId:m.id})}if(p.notes)s.notes.unshift({id:id(s,'note','NOTE-'),memberId:m.id,text:p.notes,at:now,recordedBy:actor.name});audit(s,actor,'Added member','Members',m.id,null,m);return m;
 }
 if(action==='member.edit'){const m=member(s,input.id),p=person.parse(input);if(p.birthDate&&p.birthDate>today())throw Error('Invalid birth date.');const dup=duplicate(s,p,m.id);if(dup)throw Error(`Possible duplicate member: ${dup.id}`);const before={...m};Object.assign(m,p,{name:[p.firstName,p.middleName,p.lastName].filter(Boolean).join(' ')});audit(s,actor,'Edited member','Members',m.id,before,m);return m}
 if(action==='member.status'){const m=member(s,input.id);const status=z.enum(['Active','Inactive','Non-Renewing','Archived','Restore']).parse(input.status);if(status==='Restore')requireAdmin(actor);const before={...m};if(status==='Archived')m.archived=true;else if(status==='Restore')m.archived=false;else m.status=status;m.reason=text.parse(input.reason||'');audit(s,actor,`Member ${status}`,'Members',m.id,before,m);return m}
 if(action==='member.note'){const m=member(s,input.id);const n={id:id(s,'note','NOTE-'),memberId:m.id,text:name.max(2000).parse(input.text),at:now,recordedBy:actor.name};s.notes.unshift(n);audit(s,actor,'Added note','Members',m.id,null,n);return n}
 if(action==='renew'){const m=member(s,input.id);if(m.archived)throw Error('Restore the member before renewing.');const d=membership.parse(input),pl=plan(s,d.planId);method(s,d.method);if(d.discount>pl.price)throw Error('Discount exceeds fee.');if(d.start<=m.expiry&&daysLeft(m.expiry)>=0)throw Error('Renewal must start after the current membership expires.');const before=structuredClone(m);m.previousPeriods=[...(m.previousPeriods||[]),{start:m.start,expiry:m.expiry}];m.planId=pl.id;m.planName=pl.name;m.start=d.start;m.expiry=endDate(d.start,pl.duration);m.fee=pl.price;m.status='Active';const pay=recordPayment(s,actor,{memberId:m.id,customer:m.name,type:'Membership Renewal',amount:pl.price-d.discount,discount:d.discount,method:d.method,reference:d.reference,period:`${m.start} – ${m.expiry}`});s.memberships.unshift({id:id(s,'membership','MS-'),memberId:m.id,planId:pl.id,planName:pl.name,start:m.start,end:m.expiry,amount:pay.amount,paymentId:pay.id,at:now,recordedBy:actor.name,type:'Renewal',notes:d.notes});audit(s,actor,'Renewed membership','Renewals',m.id,before,m);return m}
 if(action==='checkin'){const m=member(s,input.id);if(m.archived||m.status==='Inactive')throw Error('This member is not eligible for check-in.');const valid=s.memberships.some(x=>x.memberId===m.id&&x.start<=today()&&x.end>=today());if(!valid)throw Error('Membership expired or not yet active. Renew before checking in.');if(m.lastCheckin&&Date.now()-Date.parse(m.lastCheckin)<15*60000)throw Error('This member checked in within the last 15 minutes.');m.lastCheckin=now;const c={id:id(s,'checkin','CI-',6),memberId:m.id,name:m.name,date:today(),at:now,type:'Member',status:memberStatus(m,s.settings.threshold),recordedBy:actor.name};s.checkins.unshift(c);audit(s,actor,'Recorded check-in','Check-ins',m.id,null,c);return c}
 if(action==='walkin.create'||action==='walkin.edit'){const d=z.object({name,contact:phone.default(''),date,time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),rate:amount,method:name,paymentStatus:z.enum(['Paid','Unpaid']),notes:text.default('')}).parse(input);method(s,d.method);if(d.date>today())throw Error('Walk-in date cannot be in the future.');if(action==='walkin.edit'){const w=s.walkins.find(x=>x.id===input.id);if(!w||w.status==='Cancelled')throw Error('Walk-in unavailable.');if(w.paymentStatus==='Paid'&&(w.rate!==d.rate||w.method!==d.method||d.paymentStatus!=='Paid'))throw Error('Void the linked payment before changing paid financial details.');const before={...w};Object.assign(w,d);if(before.paymentStatus==='Unpaid'&&d.paymentStatus==='Paid')recordPayment(s,actor,{walkinId:w.id,customer:w.name,type:'Walk-in Fee',amount:w.rate,method:w.method,reference:''});audit(s,actor,'Edited walk-in','Walk-ins',w.id,before,w);return w}const w={...d,id:id(s,'walkin-'+d.date,'WI-'+d.date.replaceAll('-','')+'-',3),status:'Recorded',recordedBy:actor.name,at:now};s.walkins.unshift(w);if(d.paymentStatus==='Paid')recordPayment(s,actor,{walkinId:w.id,customer:w.name,type:'Walk-in Fee',amount:w.rate,method:w.method,reference:''});audit(s,actor,'Added walk-in','Walk-ins',w.id,null,w);return w}
 if(action==='walkin.cancel'){const w=s.walkins.find(x=>x.id===input.id);if(!w)throw Error('Walk-in not found.');if(w.paymentStatus==='Paid')throw Error('Void the linked payment before cancelling.');const before={...w};w.status='Cancelled';w.reason=name.parse(input.reason);audit(s,actor,'Cancelled walk-in','Walk-ins',w.id,before,w);return w}
 if(action==='payment.create'){const p=payment.parse(input);let customer=name.parse(input.customer||'');const m=input.memberId?member(s,input.memberId):null;const w=input.walkinId?s.walkins.find(x=>x.id===input.walkinId&&x.status!=='Cancelled'):null;if(input.walkinId&&!w)throw Error('Walk-in not found.');if(w?.paymentStatus==='Paid')throw Error('This walk-in is already paid.');if(w&&p.amount!==w.rate)throw Error('Payment must match the daily rate.');if(m)customer=m.name;if(w)customer=w.name;const pay=recordPayment(s,actor,{...p,customer,memberId:m?.id||null,walkinId:w?.id||null,type:w?'Walk-in Fee':'Other Gym Payment',notes:text.parse(input.notes||'')});if(w)w.paymentStatus='Paid';audit(s,actor,'Recorded payment','Payments',pay.id,null,pay);return pay}
 if(action==='payment.void'){requireAdmin(actor);const p=s.payments.find(x=>x.id===input.id);if(!p||p.status==='Voided')throw Error('Payment unavailable.');const before={...p};p.status='Voided';p.reason=name.parse(input.reason);p.voidedAt=now;p.voidedBy=actor.name;const w=s.walkins.find(x=>x.id===p.walkinId);if(w)w.paymentStatus='Unpaid';audit(s,actor,'Voided payment','Payments',p.id,before,p);return p}
 if(action==='plan.save'){requireAdmin(actor);const d=z.object({name,duration:z.coerce.number().int().min(1).max(3650),price:amount,description:text.default(''),active:z.boolean()}).parse(input);const existing=s.plans.find(x=>x.id===input.id),before=existing?{...existing}:null;const p=existing||{id:'PLAN-'+crypto.randomUUID()};Object.assign(p,d);if(!existing)s.plans.push(p);audit(s,actor,'Saved membership plan','Memberships',p.id,before,p);return p}
 if(action==='admin.save'){requireAdmin(actor);const d=z.object({name,username:z.string().trim().min(3).max(60).regex(/^[a-zA-Z0-9._-]+$/),email:z.string().trim().email().max(200),role:z.enum(['Super Admin','Staff']),active:z.boolean()}).parse(input);if(s.admins.some(x=>x.id!==input.id&&(x.username.toLowerCase()===d.username.toLowerCase()||x.email.toLowerCase()===d.email.toLowerCase())))throw Error('Username or email already exists.');const existing=s.admins.find(x=>x.id===input.id);if(existing?.id===actor.id&&(!d.active||d.role!=='Super Admin'))throw Error('You cannot disable or demote your own account.');if(existing?.role==='Super Admin'&&(!d.active||d.role!=='Super Admin')&&s.admins.filter(x=>x.active&&x.role==='Super Admin').length<=1)throw Error('Keep at least one active Super Admin.');const a=existing||{id:'ADMIN-'+crypto.randomUUID(),createdAt:now,lastLogin:null,sessionVersion:0};const before=existing?publicAdmin(existing):null;if(!existing||input.password){const pw=z.string().min(12).max(128).parse(input.password);if(pw!==input.confirmPassword)throw Error('Passwords do not match.');a.passwordHash=hashPassword(pw);a.sessionVersion=(a.sessionVersion||0)+1;a.mustChangePassword=true}Object.assign(a,d);if(!existing)s.admins.push(a);audit(s,actor,'Saved admin account','Admin Accounts',a.id,before,publicAdmin(a));return publicAdmin(a)}
 if(action==='settings.save'){requireAdmin(actor);const d=z.object({gymName:name,address:text,contact:phone,email:z.union([z.string().email(),z.literal('')]),logo:z.union([z.string().url().refine(v=>v.startsWith('https://')),z.literal('')]),threshold:z.coerce.number().int().min(1).max(90),walkinRate:amount,paymentMethods:z.array(z.enum(['Cash','GCash','Maya','Bank Transfer','Other'])).min(1),rules:text,dateFormat:z.enum(['YYYY-MM-DD','DD/MM/YYYY','MM/DD/YYYY']),timeFormat:z.enum(['12-hour','24-hour']),currency:z.literal('PHP')}).parse(input);const before={...s.settings};Object.assign(s.settings,d);audit(s,actor,'Changed settings','Settings','SYSTEM',before,d);return d}
 throw Error('Unknown operation.');
}


