import {type Row,type State,today} from './model';
export type TransactionPeriod='Daily'|'Monthly'|'Annual';
/** Business dates are always Philippine dates, including timestamps near UTC midnight. */
export function businessDate(value:string):string{if(/^\d{4}-\d{2}-\d{2}$/.test(value||''))return value;if(!value||Number.isNaN(Date.parse(value)))return '';return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value))}
export function periodBounds(period:TransactionPeriod,selection:string):[string,string]{if(period==='Daily'){if(!/^\d{4}-\d{2}-\d{2}$/.test(selection))return ['',''];return [selection,selection]}if(period==='Annual'){if(!/^\d{4}$/.test(selection))return ['',''];return [`${selection}-01-01`,`${selection}-12-31`]}if(!/^\d{4}-\d{2}$/.test(selection))return ['',''];const [year,month]=selection.split('-').map(Number);if(month<1||month>12)return ['',''];const last=new Date(Date.UTC(year,month,0)).getUTCDate();return [`${selection}-01`,`${selection}-${last}`]}
export function transactionRows(s:State):Row[]{return [
 ...s.payments.map(p=>({...p,eventId:'payment:'+p.id,kind:'Payment',recordId:p.id,customer:p.customer,date:businessDate(p.date||p.at),at:p.at,amount:Number(p.amount),detail:p.type,recordedBy:p.recordedBy,memberId:p.memberId,walkinId:p.walkinId})),
 ...s.memberships.map(h=>({eventId:'membership:'+h.id,recordId:h.id,kind:h.type==='Renewal'?'Renewal':'Registration',customer:s.members.find(m=>m.id===h.memberId)?.name||h.memberId,date:businessDate(h.at),at:h.at,amount:null,status:'Recorded',detail:`${h.planName}: ${h.start} to ${h.end}`,recordedBy:h.recordedBy,memberId:h.memberId})),
 ...s.walkins.map(w=>({eventId:'walkin:'+w.id,recordId:w.id,kind:'Walk-in',customer:w.name,date:businessDate(w.date),at:w.at,amount:null,status:w.status==='Cancelled'?'Cancelled':w.paymentStatus,detail:`Daily visit · ${w.time}`,recordedBy:w.recordedBy,walkinId:w.id})),
 ...s.checkins.map(c=>({eventId:'checkin:'+c.id,recordId:c.id,kind:'Check-in',customer:c.name,date:businessDate(c.date||c.at),at:c.at,amount:null,status:'Recorded',detail:c.status,recordedBy:c.recordedBy,memberId:c.memberId}))
 ].map(e=>({...e,id:e.eventId})).sort((a,b)=>b.date.localeCompare(a.date)||String(b.at||'').localeCompare(String(a.at||'')))}
export function transactionSummary(rows:Row[]){const payments=rows.filter(r=>r.kind==='Payment');return {revenue:payments.filter(p=>p.status==='Paid').reduce((n,p)=>n+p.amount,0),voided:payments.filter(p=>p.status==='Voided').reduce((n,p)=>n+p.amount,0),payments:payments.length,registrations:rows.filter(r=>r.kind==='Registration').length,renewals:rows.filter(r=>r.kind==='Renewal').length,walkins:rows.filter(r=>r.kind==='Walk-in'&&r.status!=='Cancelled').length,checkins:rows.filter(r=>r.kind==='Check-in').length,activities:rows.length}}
export function monthlyBreakdown(rows:Row[],year:string){return Array.from({length:12},(_,i)=>{const month=`${year}-${String(i+1).padStart(2,'0')}`;return {id:month,month:new Intl.DateTimeFormat('en',{month:'long',timeZone:'UTC'}).format(new Date(Date.UTC(Number(year),i,1))),...transactionSummary(rows.filter(r=>r.date.startsWith(month)))}})}
